using VotingSystem.Common;
using System.Data.Entity.Migrations;

namespace VotingSystem.DAL.Migrations
{
	public partial class MissedMigration : DbMigration
	{
		public override void Up()
		{
			AlterColumn("dbo.Answer", "CreateDate", c => c.DateTime(defaultValueSql: "GETDATE()", nullable: false));
			AlterColumn("dbo.Theme", "CreateDate", c => c.DateTime(defaultValueSql: "GETDATE()", nullable: false));
			AlterColumn("dbo.Comment", "CreateDate", c => c.DateTime(defaultValueSql: "GETDATE()", nullable: false));
			AlterColumn("dbo.User", "CreateDate", c => c.DateTime(defaultValueSql: "GETDATE()", nullable: false));
			AlterColumn("dbo.Log", "Date", c => c.DateTime(defaultValueSql: "GETDATE()", nullable: false));

			Sql(@"IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SeedTables]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SeedTables]");
			CreateStoredProcedure("SeedTables", string.Format(@"
	DELETE FROM Theme
	DELETE FROM [User]
	DELETE FROM Answer
	DELETE FROM Comment
	DELETE FROM UserProfile
	DELETE FROM [Role]

--Create Users
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email1@email.com',getdate(),1,null,getdate(),'Admin',0,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email1@email.com',getdate(),1,null,getdate(),'User1',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email2@email.com',getdate(),1,null,getdate(),'User2',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email3@email.com',getdate(),1,null,getdate(),'User3',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email4@email.com',getdate(),1,null,getdate(),'User4',0,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email5@email.com',getdate(),1,null,getdate(),'User5',0,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email6@email.com',getdate(),1,null,getdate(),'User6',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email7@email.com',getdate(),1,null,getdate(),'User7',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email8@email.com',getdate(),1,null,getdate(),'User8',0,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email9@email.com',getdate(),1,null,getdate(),'User9',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email10@email.com',getdate(),1,null,getdate(),'User10',0,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email11@email.com',getdate(),1,null,getdate(),'User11',1,null,null)
	INSERT INTO [User]([Password],[Email],[CreateDate],[IsApproved],[ApproveCode],[ApproveSendDate],[UserName],[IsLocked],[PasswordQuestion],[PasswordAnswer]) VALUES ('{0}','email12@email.com',getdate(),1,null,getdate(),'User12',0,null,null)

--Create Roles
	INSERT INTO Role(RoleName) VALUES('Admin')
	INSERT INTO Role(RoleName) VALUES('User')
	INSERT INTO Role(RoleName) VALUES('Moderator')
		
--Set users variables
	DECLARE @adminId int = (SELECT id FROM [user] WHERE username='Admin');
	DECLARE @user1 int = (SELECT id FROM [user] WHERE username='User1');
	DECLARE @user2 int = (SELECT id FROM [user] WHERE username='User2');
	DECLARE @user3 int = (SELECT id FROM [user] WHERE username='User3');
	DECLARE @user4 int = (SELECT id FROM [user] WHERE username='User4');
	DECLARE @user5 int = (SELECT id FROM [user] WHERE username='User5');
	DECLARE @user6 int = (SELECT id FROM [user] WHERE username='User6');
	DECLARE @user7 int = (SELECT id FROM [user] WHERE username='User7');
	DECLARE @user8 int = (SELECT id FROM [user] WHERE username='User8');
	DECLARE @user9 int = (SELECT id FROM [user] WHERE username='User9');
	DECLARE @user10 int = (SELECT id FROM [user] WHERE username='User10');
	DECLARE @user11 int = (SELECT id FROM [user] WHERE username='User11');
	DECLARE @user12 int = (SELECT id FROM [user] WHERE username='User12');

		
--Create UserProfiles
	INSERT INTO UserProfile VALUES (@adminId,null,null,0,0)
	INSERT INTO UserProfile VALUES (@user1,null,null,0,0)
	INSERT INTO UserProfile VALUES (@user2,null,null,2,0)
	INSERT INTO UserProfile VALUES (@user3,null,null,1,0)
	INSERT INTO UserProfile VALUES (@user4,null,null,0,0)
	INSERT INTO UserProfile VALUES (@user5,null,null,2,0)
	INSERT INTO UserProfile VALUES (@user6,null,null,1,0)
	INSERT INTO UserProfile VALUES (@user7,null,null,1,0)
	INSERT INTO UserProfile VALUES (@user8,null,null,2,0)
	INSERT INTO UserProfile VALUES (@user9,null,null,1,0)
	INSERT INTO UserProfile VALUES (@user10,null,null,0,0)
	INSERT INTO UserProfile VALUES (@user11,null,null,1,0)
	INSERT INTO UserProfile VALUES (@user12,null,null,1,0)	

--Add users to roles
	INSERT INTO UserInRoles VALUES(@adminId,(SELECT Id FROM [role] WHERE rolename='Admin'))
	INSERT INTO UserInRoles VALUES(@user1,(SELECT Id FROM [role] WHERE rolename='Admin'))
	INSERT INTO UserInRoles VALUES(@user2,(SELECT Id FROM [role] WHERE rolename='User'))
	INSERT INTO UserInRoles VALUES(@user3,(SELECT Id FROM [role] WHERE rolename='Moderator'))
	INSERT INTO UserInRoles VALUES(@user4,(SELECT Id FROM [role] WHERE rolename='User'))
	INSERT INTO UserInRoles VALUES(@user5,(SELECT Id FROM [role] WHERE rolename='User'))
	INSERT INTO UserInRoles VALUES(@user6,(SELECT Id FROM [role] WHERE rolename='Moderator'))
	INSERT INTO UserInRoles VALUES(@user7,(SELECT Id FROM [role] WHERE rolename='Moderator'))
	INSERT INTO UserInRoles VALUES(@user8,(SELECT Id FROM [role] WHERE rolename='Admin'))
	INSERT INTO UserInRoles VALUES(@user9,(SELECT Id FROM [role] WHERE rolename='Moderator'))
	INSERT INTO UserInRoles VALUES(@user10,(SELECT Id FROM [role] WHERE rolename='Moderator'))
	INSERT INTO UserInRoles VALUES(@user11,(SELECT Id FROM [role] WHERE rolename='Moderator'))
	INSERT INTO UserInRoles VALUES(@user12,(SELECT Id FROM [role] WHERE rolename='Admin'))

--Create themes
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user2,getdate(),getdate(),DATEADD(day,7,getdate()),'1Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 1',1,'Voting 1')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user11,getdate(),getdate(),DATEADD(day,7,getdate()),'2Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 2',2,'Voting 2')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user4,getdate(),getdate(),DATEADD(day,7,getdate()),'3Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 3',0,'Voting 3')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user9,getdate(),getdate(),DATEADD(day,7,getdate()),'4Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 4',2,'Voting 4')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user4,getdate(),getdate(),DATEADD(day,7,getdate()),'5Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 5',2,'Voting 5')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user10,getdate(),getdate(),DATEADD(day,7,getdate()),'6Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 6',2,'Voting 6')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user9,getdate(),getdate(),DATEADD(day,7,getdate()),'7Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 7',2,'Voting 7')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user11,getdate(),getdate(),DATEADD(day,7,getdate()),'8Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 8',2,'Voting 8')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user2,getdate(),getdate(),DATEADD(day,7,getdate()),'9Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 9',1,'Voting 9')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user7,getdate(),getdate(),DATEADD(day,7,getdate()),'10Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 10',1,'Voting 10')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user3,getdate(),getdate(),DATEADD(day,7,getdate()),'11Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 11',3,'Voting 11')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user3,getdate(),getdate(),DATEADD(day,7,getdate()),'12Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 12',3,'Voting 12')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user9,getdate(),getdate(),DATEADD(day,7,getdate()),'13Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 13',3,'Voting 13')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user3,getdate(),getdate(),DATEADD(day,7,getdate()),'14Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 14',1,'Voting 14')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user4,getdate(),getdate(),DATEADD(day,7,getdate()),'15Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 15',1,'Voting 15')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user9,getdate(),getdate(),DATEADD(day,7,getdate()),'16Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 16',3,'Voting 16')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user4,getdate(),getdate(),DATEADD(day,7,getdate()),'17Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 17',2,'Voting 17')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user7,getdate(),getdate(),DATEADD(day,7,getdate()),'18Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 18',1,'Voting 18')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user1,getdate(),getdate(),DATEADD(day,7,getdate()),'19Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 19',0,'Voting 19')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user2,getdate(),getdate(),DATEADD(day,7,getdate()),'20Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 20',0,'Voting 20')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user2,getdate(),getdate(),DATEADD(day,7,getdate()),'21Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 21',3,'Voting 21')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user2,getdate(),getdate(),DATEADD(day,7,getdate()),'22Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 22',2,'Voting 22')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user4,getdate(),getdate(),DATEADD(day,7,getdate()),'23Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 23',2,'Voting 23')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user4,getdate(),getdate(),DATEADD(day,7,getdate()),'24Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 24',2,'Voting 24')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user1,getdate(),getdate(),DATEADD(day,7,getdate()),'25Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 25',2,'Voting 25')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user11,getdate(),getdate(),DATEADD(day,7,getdate()),'26Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 26',2,'Voting 26')
	INSERT INTO THEME([UserId],[CreateDate],[StartDate],[FinishTime],[Description],[VotingText],[Status],[VotingName]) VALUES(@user8,getdate(),getdate(),DATEADD(day,7,getdate()),'27Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.','Voting Text 27',2,'Voting 27')

--set themes variables
	DECLARE @voting1 int = (SELECT id FROM theme WHERE votingName='Voting 1');
	DECLARE @voting2 int = (SELECT id FROM theme WHERE votingName='Voting 2');
	DECLARE @voting3 int = (SELECT id FROM theme WHERE votingName='Voting 3');
	DECLARE @voting4 int = (SELECT id FROM theme WHERE votingName='Voting 4');
	DECLARE @voting5 int = (SELECT id FROM theme WHERE votingName='Voting 5');
	DECLARE @voting6 int = (SELECT id FROM theme WHERE votingName='Voting 6');
	DECLARE @voting7 int = (SELECT id FROM theme WHERE votingName='Voting 7');
	DECLARE @voting8 int = (SELECT id FROM theme WHERE votingName='Voting 8');
	DECLARE @voting9 int = (SELECT id FROM theme WHERE votingName='Voting 9');
	DECLARE @voting10 int = (SELECT id FROM theme WHERE votingName='Voting 10');
	DECLARE @voting11 int = (SELECT id FROM theme WHERE votingName='Voting 11');
	DECLARE @voting12 int = (SELECT id FROM theme WHERE votingName='Voting 12');
	DECLARE @voting13 int = (SELECT id FROM theme WHERE votingName='Voting 13');
	DECLARE @voting14 int = (SELECT id FROM theme WHERE votingName='Voting 14');
	DECLARE @voting15 int = (SELECT id FROM theme WHERE votingName='Voting 15');
	DECLARE @voting16 int = (SELECT id FROM theme WHERE votingName='Voting 16');
	DECLARE @voting17 int = (SELECT id FROM theme WHERE votingName='Voting 17');
	DECLARE @voting18 int = (SELECT id FROM theme WHERE votingName='Voting 18');
	DECLARE @voting19 int = (SELECT id FROM theme WHERE votingName='Voting 19');
	DECLARE @voting20 int = (SELECT id FROM theme WHERE votingName='Voting 20');
	DECLARE @voting21 int = (SELECT id FROM theme WHERE votingName='Voting 21');
	DECLARE @voting22 int = (SELECT id FROM theme WHERE votingName='Voting 22');
	DECLARE @voting23 int = (SELECT id FROM theme WHERE votingName='Voting 23');
	DECLARE @voting24 int = (SELECT id FROM theme WHERE votingName='Voting 24');
	DECLARE @voting25 int = (SELECT id FROM theme WHERE votingName='Voting 25');
	DECLARE @voting26 int = (SELECT id FROM theme WHERE votingName='Voting 26');
	DECLARE @voting27 int = (SELECT id FROM theme WHERE votingName='Voting 27');
	
--Add comments
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting27,getdate(),'Comment Text 787515')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting16,getdate(),'Comment Text 398725')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting20,getdate(),'Comment Text 193615')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting20,getdate(),'Comment Text 65694')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting23,getdate(),'Comment Text 151209')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting12,getdate(),'Comment Text 884478')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting8,getdate(),'Comment Text 440004')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting13,getdate(),'Comment Text 383070')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting21,getdate(),'Comment Text 418178')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting24,getdate(),'Comment Text 711805')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting12,getdate(),'Comment Text 547518')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting14,getdate(),'Comment Text 791991')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting21,getdate(),'Comment Text 278181')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting14,getdate(),'Comment Text 236693')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting23,getdate(),'Comment Text 674232')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting2,getdate(),'Comment Text 305647')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting14,getdate(),'Comment Text 498681')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting20,getdate(),'Comment Text 916316')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting13,getdate(),'Comment Text 871673')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting13,getdate(),'Comment Text 863798')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting7,getdate(),'Comment Text 465209')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting24,getdate(),'Comment Text 822798')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting21,getdate(),'Comment Text 434248')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting25,getdate(),'Comment Text 669810')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting24,getdate(),'Comment Text 395168')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting20,getdate(),'Comment Text 219644')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting6,getdate(),'Comment Text 166396')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting10,getdate(),'Comment Text 921373')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting9,getdate(),'Comment Text 366427')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting14,getdate(),'Comment Text 564511')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting13,getdate(),'Comment Text 473361')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting4,getdate(),'Comment Text 150570')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting1,getdate(),'Comment Text 893876')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting2,getdate(),'Comment Text 862990')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting1,getdate(),'Comment Text 373573')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting20,getdate(),'Comment Text 317937')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting19,getdate(),'Comment Text 643156')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting2,getdate(),'Comment Text 521456')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting1,getdate(),'Comment Text 458575')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting1,getdate(),'Comment Text 104108')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting26,getdate(),'Comment Text 747235')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting11,getdate(),'Comment Text 866019')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting25,getdate(),'Comment Text 545837')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting15,getdate(),'Comment Text 145051')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting21,getdate(),'Comment Text 913251')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting22,getdate(),'Comment Text 277799')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting13,getdate(),'Comment Text 839094')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting2,getdate(),'Comment Text 325059')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting12,getdate(),'Comment Text 156540')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting10,getdate(),'Comment Text 592624')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting9,getdate(),'Comment Text 460555')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting20,getdate(),'Comment Text 336135')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting6,getdate(),'Comment Text 998099')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting4,getdate(),'Comment Text 345447')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting9,getdate(),'Comment Text 78516')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting1,getdate(),'Comment Text 817630')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting24,getdate(),'Comment Text 399426')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting9,getdate(),'Comment Text 253539')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting5,getdate(),'Comment Text 870375')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting10,getdate(),'Comment Text 42907')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting21,getdate(),'Comment Text 817501')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting20,getdate(),'Comment Text 639710')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting7,getdate(),'Comment Text 236587')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting6,getdate(),'Comment Text 42916')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting3,getdate(),'Comment Text 628571')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting23,getdate(),'Comment Text 431605')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting20,getdate(),'Comment Text 264965')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting26,getdate(),'Comment Text 449786')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting26,getdate(),'Comment Text 893382')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting3,getdate(),'Comment Text 349541')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting9,getdate(),'Comment Text 22929')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting20,getdate(),'Comment Text 123503')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting8,getdate(),'Comment Text 214237')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting15,getdate(),'Comment Text 590114')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting26,getdate(),'Comment Text 93638')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting7,getdate(),'Comment Text 353903')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting22,getdate(),'Comment Text 38420')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting27,getdate(),'Comment Text 1467')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting8,getdate(),'Comment Text 347130')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting3,getdate(),'Comment Text 79936')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting11,getdate(),'Comment Text 77300')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting20,getdate(),'Comment Text 492553')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting1,getdate(),'Comment Text 467583')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting5,getdate(),'Comment Text 607518')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting21,getdate(),'Comment Text 758101')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting4,getdate(),'Comment Text 899169')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting16,getdate(),'Comment Text 470146')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting21,getdate(),'Comment Text 125747')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting1,getdate(),'Comment Text 72737')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting19,getdate(),'Comment Text 464486')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting18,getdate(),'Comment Text 233985')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting4,getdate(),'Comment Text 538607')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting22,getdate(),'Comment Text 592594')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting20,getdate(),'Comment Text 49282')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting16,getdate(),'Comment Text 4459')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting8,getdate(),'Comment Text 400891')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting12,getdate(),'Comment Text 279505')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting23,getdate(),'Comment Text 822593')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting8,getdate(),'Comment Text 904546')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting14,getdate(),'Comment Text 298733')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting9,getdate(),'Comment Text 218134')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting24,getdate(),'Comment Text 899548')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting22,getdate(),'Comment Text 496912')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting8,getdate(),'Comment Text 409475')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting7,getdate(),'Comment Text 335489')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting1,getdate(),'Comment Text 474638')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting26,getdate(),'Comment Text 869520')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting27,getdate(),'Comment Text 842169')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting19,getdate(),'Comment Text 562502')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting23,getdate(),'Comment Text 91970')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting17,getdate(),'Comment Text 774325')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting7,getdate(),'Comment Text 55826')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting6,getdate(),'Comment Text 727423')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting2,getdate(),'Comment Text 678794')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting4,getdate(),'Comment Text 296480')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting17,getdate(),'Comment Text 29968')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting27,getdate(),'Comment Text 700183')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting24,getdate(),'Comment Text 115409')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting10,getdate(),'Comment Text 313328')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting27,getdate(),'Comment Text 23752')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting16,getdate(),'Comment Text 723194')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting11,getdate(),'Comment Text 442675')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting18,getdate(),'Comment Text 670020')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting25,getdate(),'Comment Text 325372')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting10,getdate(),'Comment Text 354613')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting1,getdate(),'Comment Text 393797')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting19,getdate(),'Comment Text 753687')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting15,getdate(),'Comment Text 775773')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting18,getdate(),'Comment Text 711124')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting8,getdate(),'Comment Text 749478')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting15,getdate(),'Comment Text 570371')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting23,getdate(),'Comment Text 796068')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting19,getdate(),'Comment Text 867091')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting25,getdate(),'Comment Text 662394')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting6,getdate(),'Comment Text 911726')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting9,getdate(),'Comment Text 728071')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting8,getdate(),'Comment Text 635054')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting19,getdate(),'Comment Text 624291')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting1,getdate(),'Comment Text 935859')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting8,getdate(),'Comment Text 397999')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting13,getdate(),'Comment Text 988177')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting11,getdate(),'Comment Text 692650')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting21,getdate(),'Comment Text 643494')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting24,getdate(),'Comment Text 833658')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting12,getdate(),'Comment Text 615353')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting26,getdate(),'Comment Text 835396')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting8,getdate(),'Comment Text 219672')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting13,getdate(),'Comment Text 661409')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting9,getdate(),'Comment Text 76545')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting11,getdate(),'Comment Text 18285')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting19,getdate(),'Comment Text 314997')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting22,getdate(),'Comment Text 582168')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting8,getdate(),'Comment Text 466092')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting23,getdate(),'Comment Text 835454')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting2,getdate(),'Comment Text 368983')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting4,getdate(),'Comment Text 347364')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting18,getdate(),'Comment Text 230752')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting20,getdate(),'Comment Text 348675')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting2,getdate(),'Comment Text 697242')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting11,getdate(),'Comment Text 536782')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting8,getdate(),'Comment Text 894306')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting19,getdate(),'Comment Text 844319')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting22,getdate(),'Comment Text 715515')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting4,getdate(),'Comment Text 629446')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting16,getdate(),'Comment Text 981925')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting24,getdate(),'Comment Text 460364')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting27,getdate(),'Comment Text 858749')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting18,getdate(),'Comment Text 457120')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting2,getdate(),'Comment Text 222469')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting2,getdate(),'Comment Text 176966')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting13,getdate(),'Comment Text 222484')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting4,getdate(),'Comment Text 179556')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting25,getdate(),'Comment Text 527983')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting8,getdate(),'Comment Text 304322')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting5,getdate(),'Comment Text 523660')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting14,getdate(),'Comment Text 83800')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting14,getdate(),'Comment Text 219')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting4,getdate(),'Comment Text 401078')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting17,getdate(),'Comment Text 847911')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting23,getdate(),'Comment Text 546351')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting22,getdate(),'Comment Text 133407')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting23,getdate(),'Comment Text 49932')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting2,getdate(),'Comment Text 379940')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting19,getdate(),'Comment Text 152984')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting23,getdate(),'Comment Text 849789')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting24,getdate(),'Comment Text 51416')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting25,getdate(),'Comment Text 989627')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting23,getdate(),'Comment Text 579308')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting10,getdate(),'Comment Text 826663')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting3,getdate(),'Comment Text 93494')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting17,getdate(),'Comment Text 820874')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting23,getdate(),'Comment Text 189140')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting13,getdate(),'Comment Text 356817')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting24,getdate(),'Comment Text 790286')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting8,getdate(),'Comment Text 859574')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting14,getdate(),'Comment Text 931082')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting5,getdate(),'Comment Text 418250')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting19,getdate(),'Comment Text 306412')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting7,getdate(),'Comment Text 588154')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting14,getdate(),'Comment Text 941030')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting6,getdate(),'Comment Text 547969')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting1,getdate(),'Comment Text 934392')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting26,getdate(),'Comment Text 617981')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting9,getdate(),'Comment Text 209858')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting3,getdate(),'Comment Text 370213')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting16,getdate(),'Comment Text 860485')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting25,getdate(),'Comment Text 204633')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting8,getdate(),'Comment Text 931979')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting19,getdate(),'Comment Text 775539')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting19,getdate(),'Comment Text 615326')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting2,getdate(),'Comment Text 346886')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting26,getdate(),'Comment Text 886929')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting15,getdate(),'Comment Text 812970')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting23,getdate(),'Comment Text 265595')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting16,getdate(),'Comment Text 252426')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user4,@voting4,getdate(),'Comment Text 213733')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user1,@voting12,getdate(),'Comment Text 663616')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting21,getdate(),'Comment Text 423872')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user3,@voting20,getdate(),'Comment Text 579505')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting25,getdate(),'Comment Text 977280')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting9,getdate(),'Comment Text 243255')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user2,@voting23,getdate(),'Comment Text 34497')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting1,getdate(),'Comment Text 121276')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting25,getdate(),'Comment Text 243852')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting11,getdate(),'Comment Text 913727')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting12,getdate(),'Comment Text 178912')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting24,getdate(),'Comment Text 909414')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting21,getdate(),'Comment Text 228536')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting21,getdate(),'Comment Text 242611')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user7,@voting8,getdate(),'Comment Text 327473')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting9,getdate(),'Comment Text 219319')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting25,getdate(),'Comment Text 982832')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting25,getdate(),'Comment Text 223233')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user6,@voting27,getdate(),'Comment Text 356545')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user8,@voting21,getdate(),'Comment Text 352854')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user10,@voting26,getdate(),'Comment Text 448898')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting13,getdate(),'Comment Text 898157')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user11,@voting10,getdate(),'Comment Text 38864')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user12,@voting9,getdate(),'Comment Text 583532')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting8,getdate(),'Comment Text 175547')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user5,@voting18,getdate(),'Comment Text 306494')
	INSERT INTO COMMENT([UserId],[ThemeId],[CreateDate],[CommentText]) VALUES(@user9,@voting17,getdate(),'Comment Text 882076')

--Create Answers
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user6,@voting26,getdate(),'AnswerText 69754')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user6,@voting15,getdate(),'AnswerText 944536')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user9,@voting1,getdate(),'AnswerText 923468')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user11,@voting6,getdate(),'AnswerText 374388')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting2,getdate(),'AnswerText 317849')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user11,@voting11,getdate(),'AnswerText 655252')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting24,getdate(),'AnswerText 491464')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting4,getdate(),'AnswerText 627596')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting7,getdate(),'AnswerText 138199')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting21,getdate(),'AnswerText 440003')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user3,@voting16,getdate(),'AnswerText 841821')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user7,@voting14,getdate(),'AnswerText 433504')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user5,@voting15,getdate(),'AnswerText 331930')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting6,getdate(),'AnswerText 767380')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user7,@voting23,getdate(),'AnswerText 115128')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user5,@voting18,getdate(),'AnswerText 578810')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user12,@voting25,getdate(),'AnswerText 995495')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user3,@voting9,getdate(),'AnswerText 91584')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user10,@voting5,getdate(),'AnswerText 817185')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user12,@voting15,getdate(),'AnswerText 575033')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user12,@voting21,getdate(),'AnswerText 138913')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting23,getdate(),'AnswerText 729037')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user5,@voting9,getdate(),'AnswerText 83324')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user10,@voting13,getdate(),'AnswerText 412559')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting16,getdate(),'AnswerText 582623')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting9,getdate(),'AnswerText 864932')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user11,@voting10,getdate(),'AnswerText 603575')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting19,getdate(),'AnswerText 72369')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting14,getdate(),'AnswerText 256696')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting2,getdate(),'AnswerText 640283')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting3,getdate(),'AnswerText 491250')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting26,getdate(),'AnswerText 605322')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting13,getdate(),'AnswerText 220872')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user9,@voting16,getdate(),'AnswerText 20344')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user11,@voting25,getdate(),'AnswerText 669913')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting4,getdate(),'AnswerText 329764')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user10,@voting20,getdate(),'AnswerText 272947')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user12,@voting9,getdate(),'AnswerText 26515')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user3,@voting18,getdate(),'AnswerText 722340')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user4,@voting22,getdate(),'AnswerText 139860')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user7,@voting23,getdate(),'AnswerText 801020')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user3,@voting27,getdate(),'AnswerText 10842')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting17,getdate(),'AnswerText 497888')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user10,@voting6,getdate(),'AnswerText 964257')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user9,@voting1,getdate(),'AnswerText 805318')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user6,@voting24,getdate(),'AnswerText 708535')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user9,@voting5,getdate(),'AnswerText 841045')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user9,@voting9,getdate(),'AnswerText 797876')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting3,getdate(),'AnswerText 526440')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user9,@voting25,getdate(),'AnswerText 421730')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user10,@voting14,getdate(),'AnswerText 127215')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting7,getdate(),'AnswerText 226667')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting9,getdate(),'AnswerText 718058')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user5,@voting2,getdate(),'AnswerText 749606')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user3,@voting12,getdate(),'AnswerText 157257')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user8,@voting25,getdate(),'AnswerText 196091')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting20,getdate(),'AnswerText 226165')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user10,@voting26,getdate(),'AnswerText 364066')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user7,@voting18,getdate(),'AnswerText 608235')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user1,@voting27,getdate(),'AnswerText 44767')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user11,@voting20,getdate(),'AnswerText 858867')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user3,@voting12,getdate(),'AnswerText 690630')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting13,getdate(),'AnswerText 381161')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting5,getdate(),'AnswerText 101267')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user11,@voting8,getdate(),'AnswerText 701979')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user5,@voting19,getdate(),'AnswerText 732822')
	INSERT INTO Answer([UserId],[ThemeId],[CreateDate],[AnswerText]) VALUES(@user2,@voting6,getdate(),'AnswerText 588528')
"
	, SecurityHelper.CreateHash("password")));

			Sql("EXEC SeedTables");
		}

		public override void Down()
		{
		}
	}
}
