// <auto-generated />
namespace VotingSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class SetNotNullFieldsInTheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetNotNullFieldsInTheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201402181151222_SetNotNullFieldsInTheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
